import { createStore, applyMiddleware, compose } from 'redux'
import thunk from 'redux-thunk'
import createLogger from 'redux-logger'

import locations from './reducers/locations'

const persistedState = {
  locationsById: {
    'NT_slcvtDdQxNuhascaVc1.yD': {
      id: 'NT_slcvtDdQxNuhascaVc1.yD',
      city: 'Sahibzada Ajit Singh Nagar',
      state: 'PB',
      country: 'India',
      latitude: 30.70347,
      longitude: 76.69162,
      currently: {
        time: 1541516400,
        summary: 'Clear',
        icon: 'clear-night',
        precipProbability: 0,
        temperature: 18.82,
        apparentTemperature: 18.82,
        humidity: 0.42,
        windSpeed: 10.03,
      },
      hourly: {
        summary: 'Clear throughout the day.',
        icon: 'clear-day',
        data: [
          {
            time: 1541514600,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 19.31,
            apparentTemperature: 19.31,
            humidity: 0.41,
            windSpeed: 10.4,
          },
          {
            time: 1541518200,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 18.22,
            apparentTemperature: 18.22,
            humidity: 0.43,
            windSpeed: 9.61,
          },
          {
            time: 1541521800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 17.34,
            apparentTemperature: 17.34,
            humidity: 0.45,
            windSpeed: 8.58,
          },
          {
            time: 1541525400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 16.64,
            apparentTemperature: 16.64,
            humidity: 0.46,
            windSpeed: 7.66,
          },
          {
            time: 1541529000,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 15.98,
            apparentTemperature: 15.98,
            humidity: 0.48,
            windSpeed: 7.15,
          },
          {
            time: 1541532600,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 15.27,
            apparentTemperature: 15.27,
            humidity: 0.49,
            windSpeed: 7.02,
          },
          {
            time: 1541536200,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 14.55,
            apparentTemperature: 14.55,
            humidity: 0.51,
            windSpeed: 7.08,
          },
          {
            time: 1541539800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 13.75,
            apparentTemperature: 13.75,
            humidity: 0.52,
            windSpeed: 7.13,
          },
          {
            time: 1541543400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 12.97,
            apparentTemperature: 12.97,
            humidity: 0.53,
            windSpeed: 7.13,
          },
          {
            time: 1541547000,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 12.66,
            apparentTemperature: 12.66,
            humidity: 0.52,
            windSpeed: 7.1,
          },
          {
            time: 1541550600,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 13.02,
            apparentTemperature: 13.02,
            humidity: 0.5,
            windSpeed: 6.87,
          },
          {
            time: 1541554200,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 13.86,
            apparentTemperature: 13.86,
            humidity: 0.48,
            windSpeed: 6.44,
          },
          {
            time: 1541557800,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 15.22,
            apparentTemperature: 15.22,
            humidity: 0.45,
            windSpeed: 6.18,
          },
          {
            time: 1541561400,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 17.28,
            apparentTemperature: 17.28,
            humidity: 0.41,
            windSpeed: 6.57,
          },
          {
            time: 1541565000,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 19.82,
            apparentTemperature: 19.82,
            humidity: 0.36,
            windSpeed: 7.52,
          },
          {
            time: 1541568600,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 22.32,
            apparentTemperature: 22.32,
            humidity: 0.31,
            windSpeed: 8.67,
          },
          {
            time: 1541572200,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 24.29,
            apparentTemperature: 24.29,
            humidity: 0.28,
            windSpeed: 9.8,
          },
          {
            time: 1541575800,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 25.58,
            apparentTemperature: 25.58,
            humidity: 0.26,
            windSpeed: 10.91,
          },
          {
            time: 1541579400,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 26.12,
            apparentTemperature: 26.12,
            humidity: 0.25,
            windSpeed: 11.65,
          },
          {
            time: 1541583000,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 25.74,
            apparentTemperature: 25.74,
            humidity: 0.26,
            windSpeed: 11.39,
          },
          {
            time: 1541586600,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 24.51,
            apparentTemperature: 24.51,
            humidity: 0.28,
            windSpeed: 10.15,
          },
          {
            time: 1541590200,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 22.89,
            apparentTemperature: 22.89,
            humidity: 0.32,
            windSpeed: 8.72,
          },
          {
            time: 1541593800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 21.29,
            apparentTemperature: 21.29,
            humidity: 0.35,
            windSpeed: 7.84,
          },
          {
            time: 1541597400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 19.66,
            apparentTemperature: 19.66,
            humidity: 0.39,
            windSpeed: 7.47,
          },
          {
            time: 1541601000,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 18.12,
            apparentTemperature: 18.12,
            humidity: 0.42,
            windSpeed: 7.24,
          },
          {
            time: 1541604600,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 16.99,
            apparentTemperature: 16.99,
            humidity: 0.45,
            windSpeed: 6.98,
          },
          {
            time: 1541608200,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 16.24,
            apparentTemperature: 16.24,
            humidity: 0.48,
            windSpeed: 6.63,
          },
          {
            time: 1541611800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 15.72,
            apparentTemperature: 15.72,
            humidity: 0.49,
            windSpeed: 6.28,
          },
          {
            time: 1541615400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 15.23,
            apparentTemperature: 15.23,
            humidity: 0.5,
            windSpeed: 5.95,
          },
          {
            time: 1541619000,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 14.69,
            apparentTemperature: 14.69,
            humidity: 0.51,
            windSpeed: 5.68,
          },
          {
            time: 1541622600,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 14.14,
            apparentTemperature: 14.14,
            humidity: 0.51,
            windSpeed: 5.47,
          },
          {
            time: 1541626200,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 13.47,
            apparentTemperature: 13.47,
            humidity: 0.52,
            windSpeed: 5.39,
          },
          {
            time: 1541629800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 12.77,
            apparentTemperature: 12.77,
            humidity: 0.52,
            windSpeed: 5.41,
          },
          {
            time: 1541633400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 12.52,
            apparentTemperature: 12.52,
            humidity: 0.52,
            windSpeed: 5.42,
          },
          {
            time: 1541637000,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 12.98,
            apparentTemperature: 12.98,
            humidity: 0.51,
            windSpeed: 5.2,
          },
          {
            time: 1541640600,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 13.95,
            apparentTemperature: 13.95,
            humidity: 0.51,
            windSpeed: 4.63,
          },
          {
            time: 1541644200,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 15.39,
            apparentTemperature: 15.39,
            humidity: 0.49,
            windSpeed: 4.18,
          },
          {
            time: 1541647800,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 17.43,
            apparentTemperature: 17.43,
            humidity: 0.46,
            windSpeed: 4.35,
          },
          {
            time: 1541651400,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 19.81,
            apparentTemperature: 19.81,
            humidity: 0.42,
            windSpeed: 5.07,
          },
          {
            time: 1541655000,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 22.02,
            apparentTemperature: 22.02,
            humidity: 0.38,
            windSpeed: 6.07,
          },
          {
            time: 1541658600,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 23.74,
            apparentTemperature: 23.74,
            humidity: 0.34,
            windSpeed: 5.46,
          },
          {
            time: 1541662200,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 24.93,
            apparentTemperature: 24.93,
            humidity: 0.31,
            windSpeed: 0.77,
          },
          {
            time: 1541665800,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 25.51,
            apparentTemperature: 25.51,
            humidity: 0.29,
            windSpeed: 5.41,
          },
          {
            time: 1541669400,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 25.29,
            apparentTemperature: 25.29,
            humidity: 0.29,
            windSpeed: 5.65,
          },
          {
            time: 1541673000,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 24.32,
            apparentTemperature: 24.32,
            humidity: 0.31,
            windSpeed: 4.1,
          },
          {
            time: 1541676600,
            summary: 'Clear',
            icon: 'clear-day',
            precipProbability: 0,
            temperature: 22.89,
            apparentTemperature: 22.89,
            humidity: 0.34,
            windSpeed: 5.44,
          },
          {
            time: 1541680200,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 21.37,
            apparentTemperature: 21.37,
            humidity: 0.37,
            windSpeed: 5.71,
          },
          {
            time: 1541683800,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 19.76,
            apparentTemperature: 19.76,
            humidity: 0.4,
            windSpeed: 6.1,
          },
          {
            time: 1541687400,
            summary: 'Clear',
            icon: 'clear-night',
            precipProbability: 0,
            temperature: 18.15,
            apparentTemperature: 18.15,
            humidity: 0.43,
            windSpeed: 6.65,
          },
        ],
      },
      daily: {
        summary: 'No precipitation throughout the week, with high temperatures bottoming out at 26°C on Thursday.',
        icon: 'clear-day',
        data: [
          {
            time: 1541442600,
            summary: 'Clear throughout the day.',
            icon: 'clear-day',
            moonPhase: 0.95,
            precipProbability: 0,
            temperatureHigh: 26.21,
            temperatureLow: 12.66,
            apparentTemperatureHigh: 26.21,
            apparentTemperatureLow: 12.66,
            humidity: 0.42,
            windSpeed: 10.38,
          },
          {
            time: 1541529000,
            summary: 'Clear throughout the day.',
            icon: 'clear-day',
            moonPhase: 0.98,
            precipProbability: 0,
            temperatureHigh: 26.12,
            temperatureLow: 12.52,
            apparentTemperatureHigh: 26.12,
            apparentTemperatureLow: 12.52,
            humidity: 0.41,
            windSpeed: 7.31,
          },
          {
            time: 1541615400,
            summary: 'Clear throughout the day.',
            icon: 'clear-day',
            moonPhase: 0.03,
            precipProbability: 0,
            temperatureHigh: 25.51,
            temperatureLow: 13,
            apparentTemperatureHigh: 25.51,
            apparentTemperatureLow: 13,
            humidity: 0.43,
            windSpeed: 2.46,
          },
          {
            time: 1541701800,
            summary: 'Clear throughout the day.',
            icon: 'clear-day',
            moonPhase: 0.06,
            precipProbability: 0,
            temperatureHigh: 26.48,
            temperatureLow: 13.86,
            apparentTemperatureHigh: 26.48,
            apparentTemperatureLow: 13.86,
            humidity: 0.42,
            windSpeed: 1.88,
          },
          {
            time: 1541788200,
            summary: 'Partly cloudy starting in the afternoon, continuing until evening.',
            icon: 'partly-cloudy-day',
            moonPhase: 0.09,
            precipProbability: 0,
            temperatureHigh: 26.64,
            temperatureLow: 14.35,
            apparentTemperatureHigh: 26.64,
            apparentTemperatureLow: 14.35,
            humidity: 0.37,
            windSpeed: 1.67,
          },
          {
            time: 1541874600,
            summary: 'Clear throughout the day.',
            icon: 'clear-day',
            moonPhase: 0.12,
            precipProbability: 0,
            temperatureHigh: 26.97,
            temperatureLow: 14.28,
            apparentTemperatureHigh: 26.97,
            apparentTemperatureLow: 14.28,
            humidity: 0.37,
            windSpeed: 2.04,
          },
          {
            time: 1541961000,
            summary: 'Partly cloudy starting in the afternoon, continuing until evening.',
            icon: 'partly-cloudy-day',
            moonPhase: 0.15,
            precipProbability: 0,
            temperatureHigh: 26.54,
            temperatureLow: 17.28,
            apparentTemperatureHigh: 26.54,
            apparentTemperatureLow: 17.28,
            humidity: 0.32,
            windSpeed: 4.75,
          },
          {
            time: 1542047400,
            summary: 'Mostly cloudy starting in the afternoon.',
            icon: 'partly-cloudy-night',
            moonPhase: 0.18,
            precipProbability: 0.12,
            temperatureHigh: 25.91,
            temperatureLow: 16.5,
            apparentTemperatureHigh: 25.91,
            apparentTemperatureLow: 16.5,
            humidity: 0.38,
            windSpeed: 7.89,
          },
        ],
      },
    },
  },
  ids: ['NT_slcvtDdQxNuhascaVc1.yD'],
  cardState: 'EXPANDED',
  expandedCardId: 'NT_slcvtDdQxNuhascaVc1.yD',
}

const configureStore = () => {
  // Apply middlewares.
  const middlewares = [thunk]
  if (process.env.NODE_ENV !== 'production') middlewares.push(createLogger)

  // Use Redux DevTools in development.
  /* eslint-disable no-underscore-dangle */
  const storeEnhancers =
    process.env.NODE_ENV !== 'production' && window.__REDUX_DEVTOOLS_EXTENSION__
      ? compose(
          applyMiddleware(...middlewares),
          window.__REDUX_DEVTOOLS_EXTENSION__()
        )
      : applyMiddleware(...middlewares)
  /* eslint-enable */

  return createStore(locations, persistedState, storeEnhancers)
}

export default configureStore
