const CARD_EXPANDED = 'CARD_EXPANDED'
const CARD_SHRINKED = 'CARD_SHRINKED'
const CARD_DELETED = 'CARD_DELETED'
const FETCH_LOCATION_DATA_REQUEST = 'FETCH_LOCATION_DATA_REQUEST'
const FETCH_LOCATION_DATA_SUCCESS = 'FETCH_LOCATION_DATA_SUCCESS'
const FETCH_LOCATION_DATA_FAILURE = 'FETCH_LOCATION_DATA_FAILURE'

export {
  CARD_EXPANDED,
  CARD_SHRINKED,
  CARD_DELETED,
  FETCH_LOCATION_DATA_REQUEST,
  FETCH_LOCATION_DATA_SUCCESS,
  FETCH_LOCATION_DATA_FAILURE,
}
