const ADD_LOCATION = 'ADD_LOCATION'
const CARD_EXPANDED = 'CARD_EXPANDED'
const CARD_SHRINKED = 'CARD_SHRINKED'
const CARD_DELETED = 'CARD_DELETED'
const LOCATION_DATA_FETCHED = 'LOCATION_DATA_FETCHED'

export { ADD_LOCATION, CARD_EXPANDED, CARD_SHRINKED, CARD_DELETED, LOCATION_DATA_FETCHED }
